---
before_install: true
install: true

# https://www.jeffgeerling.com/blog/2016/how-i-test-ansible-configuration-on-7-different-oses-docker
services: docker

env:
  - distro: centos7
  # - distro: ubuntu1604

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim
  # - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  # - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Make sure phantomjs is actually installed/available via symlink
  # TODO: determine the best test here..
  # - 'docker exec --tty ${container_id} env TERM=xterm phantomjs --version'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
