---
- name: Download ssh keys for library staff
  authorized_key:
    user: '{{ ssh_keys_ad_account }}'
    state: present
    key: https://github.com/{{ item }}.keys
  with_items: '{{ ssh_keys_github_accounts }}'
  tags: ssh-keys
