---

# Copy ssh keys to root

- name: Get {{ user }}'s passwd entry
  getent:
    database: passwd
    key: '{{ user }}'

- name: Save {{ user }}'s passwd fields
  set_fact:
    uid:  '{{ getent_passwd[user][1] }}'
    gid:  '{{ getent_passwd[user][2] }}'
    home: '{{ getent_passwd[user][4] }}'

- name: Ensure {{ user }}'s ssh directory exists
  file:
    path: '{{ home }}/.ssh'
    state: directory
    owner: '{{ uid }}'
    group: '{{ gid }}'
    mode: 0700

- name: 'Apply ssh keys to {{ user }}'
  copy:
    dest: '{{ home }}/.ssh/authorized_keys'
    src: '{{ item }}'
    owner: '{{ uid }}'
    group: '{{ gid }}'
    mode: 0644
  with_first_found:
    - 'authorized_keys-{{ user }}-{{ ansible_hostname }}'
    - 'authorized_keys-{{ user }}'
    - 'authorized_keys-{{ ansible_hostname }}'
    - 'authorized_keys'
